#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

echo "Tests started at…"
date "+%H:%M:%S"

# setup environment
SALT_ROOT="$(cd "$(dirname "$0")"/.. && pwd)"
export SALT_ROOT
export SALT_ENV="test"

export PATH="$SALT_ROOT/src:$PATH"

# run tests
echo "Running tests …"
date "+%H:%M:%S"

# run tests.
script/test
