#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update

test -z "$SALT_ENV" &&
  SALT_ENV='development'

# boot the app and any other necessary processes.
sass --watch src/salt.scss:build/salt.css --style expanded
